---
site_name: Jakob Stender Guldberg
site_url: https://jakob1379.github.io/
# repo_url: https://github.com/jakob1379
# repo_name: My Github
site_description: Contact details and blog posts by Jakob Stender Guldberg
copyright: Copyright &copy; 2025 Jakob Stender Guldberg
theme:
  name: material
  variant: classic
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  # logo: assets/logo.png
  # favicon: images/favicon.png
  palette:
    # Palette toggle for automatic mode
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    # - header.autohide  # This feature is incompatible with the parallax effect
    # - navigation.tabs.sticky
    # - search.highlight
    # - search.share
    # - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
extra_css: [stylesheets/extra.css]
extra_javascript: [javascripts/extra.js]
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jakob1379
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jakobguldberg/
      name: LinkedIn
    - icon: fontawesome/brands/python
      link: https://pypi.org/user/jakob1379/
      name: PyPi
plugins:
  - social
  - minify_html
  # - search
  - blog:
      blog_toc: false
      authors_file: .authors
      post_readtime: true
      draft: true
      authors_profiles: true
markdown_extensions:
  - pymdownx.arithmatex
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
